#script to generate data for causal simulation
if (!require("here")){
  install.packages("here")
  library("here")
}
if (!require("magrittr")){
  install.packages("magrittr")
  library("magrittr")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
  library("tidyverse")
}
if (!require("SingleCellExperiment")){
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::install("SingleCellExperiment")
  library("SingleCellExperiment")
} 
if (!require("anndata")){
  install.packages("anndata")
  library("anndata")
}

#load objects
load(here("data","ref","mapping","mmu_hsa_mapping.rda"))

#load functions
source(here("src","tools","sparse_mat_util.R"))
source(here("src","tools","munge_sce_mat.R"))

##### load random gene sets generated by null_sim_data_proc.R ####
zscore_dir <- here("data","gwas","causal_sim","zscore")
scdrs_dir <- here("data","gwas","causal_sim","scdrs_gs")
magma_raw_dir <- here("data","gwas","causal_sim","magma_raw")
expr_dir <- here("data","expr","null_sim","expr_rda_rs")
h5ad_dir <- here("data","expr","null_sim","expr_h5ad_rs")
#load all random gene sets generated
z_score_list <- list.files(zscore_dir) %>%
  set_names(gsub(pattern = ".genes.out", replacement = "", x = ., fixed = T)) %>%
  map(~read.table(file=paste0(zscore_dir,"/",.x), header = T)) %>%
  map(~left_join(.x, distinct(mmu_hsa_mapping, hsa_entrez, mmu_symbol), by = c("GENE"="hsa_entrez"))) #join with gene mapping

#load expression data
expr_list <- list.files(expr_dir) %>%
  set_names(gsub(pattern = ".rda", replacement = "", x = ., fixed = T)) %>%
  map(~{load(paste0(expr_dir,"/",.x)); return(sce)})  %>%
  map(~{colnames(.x) <- .x$cellid; .x})

#see if they are in original expression data sets
#also get the mean ZSTAT by gene symbol
z_score_list <- z_score_list %>%
  map(~mutate(.x, in_expr = ifelse(mmu_symbol %in% rownames(expr_list$expr_ds_1), T, F))) %>%
  map(~filter(.x, in_expr)) %>% 
  map(~group_by(.x, mmu_symbol)) %>%
  map(~mutate(.x, ZSTAT = mean(ZSTAT))) %>%
  map(~ungroup(.x)) %>%
  map(~distinct(.x,mmu_symbol, .keep_all = T)) %>%
  map(~arrange(.x, -ZSTAT)) 

##### function definition #####
### perturb expression matrix 
#parameter: cell_ids and gene_eff_vecs are two lists, where each element represents the cells and genes to be perturbed
perturb_count_matrix <- function(sce_mat, gene_eff_vecs,cell_ids, round_matrix = T, zero_to_positive = T){
  #gene effect must have the same order as the gene columns
  #gene effect vector must have names
  if (class(sce_mat)[1] == "SingleCellExperiment"){
    perturbed_mat = assay(sce_mat, "counts")
  }else{
    perturbed_mat <- sce_mat
  }
  
  all_cell_ids <- cell_ids %>% purrr::reduce(~unique(c(.x,.y)))
  all_gene_names <- gene_eff_vecs %>% map(~names(.x)) %>% purrr::reduce(~unique(c(.x,.y)))
  print(head(all_gene_names))
  
  if(any(!all_gene_names %in% rownames(perturbed_mat)) | any(!all_cell_ids %in% colnames(perturbed_mat)) ){
   # print(rownames(perturbed_mat)[!rownames(perturbed_mat) %in% all_gene_names])
  #  print(colnames(perturbed_mat[!colnames(perturbed_mat) %in% all_cell_ids]))
    stop("some cell ids / gene names may not exist in the matrix")
  }
  
  all_mat <- as.matrix(perturbed_mat[match(all_gene_names, rownames(perturbed_mat)), match(all_cell_ids, colnames(perturbed_mat))])
  
  gene_eff_vecs <- 
  
  perturbed_mat_list <- map2(gene_eff_vecs,cell_ids, ~all_mat[match(names(.x), rownames(all_mat)), match(.y, colnames(all_mat))]) %>%
    map2(gene_eff_vecs, ~sweep(.x, MARGIN = 1, STATS = .y, FUN = "*")) %>%
    map(~floor(.x)) %>%
    map2(gene_eff_vecs, ~{.x[.x==0 & .y>1] <-1; .x})
  
  walk(perturbed_mat_list, function(x) all_mat[match(rownames(x), rownames(all_mat)), match(colnames(x),colnames(all_mat))] <<- x)
  
  return(all_mat)
}

##### 1. standard perturbation: 250 disease genes and 750 cell type specific genes ####
standard_gene_anno_dir <- here("data","gwas","causal_sim","standard","gene_anno")
standard_cell_anno_dir <- here("data","expr","causal_sim","standard","cell_anno")
standard_perturbed_expr_dir <- here("data","expr","causal_sim","standard","perturbed_expr")

##sample random cells as target cell types
set.seed(98)
standard_cell_anno <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map(~mutate(.x, is_target = ifelse(1:n() %in% sample(n(), 100), T, F))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(is_target, "target_cell_type", cell_ontology_class)))

#only perturb genes with expression in more than 10 cells
standard_ok_gene_list <- map(standard_cell_anno, ~pull(filter(.x, is_target), cellid)) %>%
  map2(expr_list, ~assay(.y, "counts")[, which(colnames(.y) %in% .x)]>0) %>%
  map(~rowSums(.x)) %>%
  map(~names(which(.x > 10)))

##gene anno
set.seed(100)
#filter out genes that are not prevalently expressed
standard_gene_anno <- z_score_list %>% 
  map(~{zscore_df <- .x
    map(standard_ok_gene_list, ~mutate(zscore_df, in_perturb_list = ifelse(mmu_symbol %in% .x, T,F)))}) %>%
  map(~map(.x, ~filter(.x, in_perturb_list))) %>%
  map(~map(.x, ~arrange(.x,-ZSTAT)))

#choose genes
standard_gene_anno = standard_gene_anno %>%
  map(~map(.x, ~mutate(.x, may_be_causal = ifelse(ZSTAT>0 & 1:n() <= 1000 , T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_causal = ifelse(mmu_symbol %in% sample(filter(., may_be_causal)$mmu_symbol, 250), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific = ifelse(mmu_symbol %in% sample(filter(., !may_be_causal)$mmu_symbol, 750), T, F)))) 

#write out gene annotation table and cell annotation table
map2(standard_cell_anno, names(standard_cell_anno), ~write.table(.x, file = paste0(standard_cell_anno_dir, "/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))
map2(standard_cell_anno %>% map(~mutate(.x, cell_ontology_class = new_cell_ontology_class)), 
     names(standard_cell_anno), ~write.table(.x, file = paste0( "data/expr/causal_sim/standard_scdesign3_model/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))
#
map2(standard_gene_anno, names(standard_gene_anno), ~{
  gs_name <- .y
  map2(.x,names(.x), ~write.table(.x,file= paste0(standard_gene_anno_dir, "/",gs_name,".", .y,".gene_anno.txt"), quote = F,row.names = F))})

### perturb expression
effect_size = seq(0, 2, 0.1) %>% set_names(paste0("es_", format(.,digits = 1)))
#write out perturbed expression matrix
map2(effect_size, names(effect_size), ~{
  es <- .x
  es_name <- .y
  dir.create(paste0(standard_perturbed_expr_dir, "/",es_name), showWarnings = FALSE)
  map2(standard_gene_anno, names(standard_gene_anno), ~{
    gs_name <- .y
    map2(.x, names(.x), ~{
      expr_name <- .y
      gene_list <- filter(.x, is_causal | is_ct_specific) %>% pull(mmu_symbol)
      gene_eff_vec <- rep(2^es, length(gene_list)) %>% set_names(gene_list)
      cell_list <- standard_cell_anno[[expr_name]]$cellid[standard_cell_anno[[expr_name]]$new_cell_ontology_class == "target_cell_type"]
      out_mat <- perturb_count_matrix(expr_list[[expr_name]], list(gene_eff_vec), list(cell_list))
      write.table(as.matrix(out_mat), file = paste0(standard_perturbed_expr_dir, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})


#write out parameter data frame
## write out parameter df 
standard_para_df <- expand_grid(es_name = names(effect_size),
                               gs_name = names(z_score_list),
                               expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(standard_perturbed_expr_dir, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(standard_gene_anno_dir, "/", gs_name,".",expr_name, ".gene_anno.txt"),
         cell_anno_file = paste0(standard_cell_anno_dir, "/", expr_name, ".cell_anno.txt"))

#
write.table(standard_para_df, file = paste0(standard_perturbed_expr_dir, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)



##### 2. perturbation with varying disease gene ratio #####
gene_anno_dir <- here("data","gwas","causal_sim","varying_gene_ratio","gene_anno")
cell_anno_dir <- here("data","expr","causal_sim","varying_gene_ratio","cell_anno")
perturbed_expr_dir <- here("data","expr","causal_sim","varying_gene_ratio","perturbed_expr")

set.seed(100)
vary_gr_gene_anno <- z_score_list %>%
  map(~mutate(.x, may_be_causal = ifelse(ZSTAT>0 & 1:n() <= 1000 , T, F), may_be_ct_specific = ifelse(ZSTAT>0 & 1:n() > 1000 , T, F))) 

gene_ratio <- seq(0.1, 1, 0.1) %>% 
  set_names(paste0("gr","_", format(.,digits = 1)))

vary_gr_gene_anno <- map(gene_ratio, ~{
  gr <- .x
  map(gene_anno, ~mutate(.x, is_causal = ifelse(mmu_symbol %in% sample(filter(., may_be_causal)$mmu_symbol, 1000*gr), T, F)) %>%
        mutate(is_ct_specific = ifelse(mmu_symbol %in% sample(filter(., may_be_ct_specific)$mmu_symbol, 1000 - 1000*gr), T, F)))
})

map2(vary_gr_gene_anno, names(vary_gr_gene_anno), ~{
  gr_name <- .y
  map2(.x,names(.x), ~write.table(.x, file= paste0(gene_anno_dir, "/", gr_name,".",.y,".gene_anno.txt"), quote = F,row.names = F))
})

##sample random cells as target cell types
set.seed(98)
vary_gr_cell_anno <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map(~mutate(.x, is_target = ifelse(1:n() %in% sample(n(), 100), T, F)))  %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(is_target, "target_cell_type", cell_ontology_class)))

#write out gene annotation table and cell annotation table
map2(vary_gr_cell_anno, names(vary_gr_cell_anno), ~write.table(.x, file = paste0(cell_anno_dir, "/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))

#write out
map2(vary_gr_gene_anno, names(vary_gr_gene_anno), ~{
  gr_name <- .y
  dir.create(paste0(perturbed_expr_dir, "/",gr_name), showWarnings = FALSE)
  map2(.x, names(.x), ~{
    gene_list <- filter(.x, is_causal | is_ct_specific) %>% pull(mmu_symbol)
    gene_eff_vec <- rep(2^0.5, length(gene_list)) %>% set_names(gene_list)
    gs_name <- .y
    map2(vary_gr_cell_anno, names(vary_gr_cell_anno), ~{
      eff_mat <- assay(expr_list[[.y]], "counts")[match(names(gene_eff_vec), rownames(expr_list[[.y]])), which(.x$is_target)] %>% 
        set_colnames(.x$cellid[which(.x$is_target)])
      out_mat <- perturb_count_matrix(eff_mat, gene_eff_vec)
      write.table(as.matrix(out_mat), file = paste0(perturbed_expr_dir, "/",gr_name, "/", gs_name,".",.y,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})


## write out parameter df 
vary_gr_para_df <- expand_grid(gr_name = names(gene_ratio),
                                gs_name = names(z_score_list),
                                expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir, "/",gr_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir, "/",gr_name,".", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", expr_name, ".cell_anno.txt"))

#
write.table(vary_gr_para_df, file = paste0(perturbed_expr_dir, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)



##### 3. perturbation with varying ratio of cells (of a cell type) are perturbed#####
gene_anno_dir <- here("data","gwas","causal_sim","varying_cell_ratio","gene_anno")
cell_anno_dir <- here("data","expr","causal_sim","varying_cell_ratio","cell_anno")
perturbed_expr_dir <- here("data","expr","causal_sim","varying_cell_ratio","perturbed_expr")
perturbed_expr_dir_all_cells <- here("data","expr","causal_sim","varying_cell_ratio","perturbed_expr_all_cells")

set.seed(100)
vary_cr_gene_anno <- z_score_list %>%
  map(~mutate(.x, may_be_causal = ifelse(ZSTAT>0 & 1:n() <= 1000 , T, F), may_be_ct_specific = ifelse(ZSTAT>0 & 1:n() > 1000 , T, F))) %>%
  map(~mutate(.x, is_causal = ifelse(mmu_symbol %in% sample(filter(., may_be_causal)$mmu_symbol, 250), T, F))) %>%
  map(~mutate(.x, is_ct_specific = ifelse(mmu_symbol %in% sample(filter(., may_be_ct_specific)$mmu_symbol, 750), T, F))) 

map2(vary_cr_gene_anno, names(vary_cr_gene_anno), ~write.table(.x, file= paste0(gene_anno_dir, "/", .y,".gene_anno.txt"), quote = F,row.names = F))

##sample random cells as target cell types and random cells as perturbed cell types
set.seed(98)
vary_cr_cell_anno <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map(~mutate(.x, is_target = ifelse(1:n() %in% sample(n(), 100), T, F))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(is_target, "target_cell_type", cell_ontology_class)))

#cell ratio
cell_ratio <- seq(0.1, 1, 0.1) %>% 
  set_names(paste0("cr","_", format(.,digits = 1)))

vary_cr_cell_anno <- map(cell_ratio, ~{
  cr <- .x
  map(vary_cr_cell_anno, ~mutate(.x, is_perturbed = ifelse(cellid %in% sample(filter(., is_target)$cellid, 100*cr), T, F)))
})

#write out cell annotation table
map2(vary_cr_cell_anno, names(vary_cr_cell_anno), ~{
  cr_name <- .y
  map2(.x,names(.x), ~write.table(.x, file= paste0(cell_anno_dir, "/",cr_name,".",.y,".cell_anno.txt"), quote = F,row.names = F, sep = "\t"))
})


#write out perturbed matrix
map2(vary_cr_cell_anno, names(vary_cr_cell_anno), ~{
  cr_name <- .y
  dir.create(paste0(perturbed_expr_dir, "/",cr_name), showWarnings = FALSE)
  map2(.x, names(.x), ~{
    cell_anno <- .x
    target_cell_list <- filter(cell_anno, is_target)$cellid
    perturbed_cell_list <- filter(cell_anno, is_perturbed)$cellid
    expr_name <- .y
    map2(vary_cr_gene_anno, names(vary_cr_gene_anno), ~{
      gene_list <- filter(.x, is_causal | is_ct_specific) %>% pull(mmu_symbol)
      gene_eff_vec <- rep(2^0.5, length(gene_list)) %>% set_names(gene_list)
      gs_name <- .y
      eff_mat <- assay(expr_list[[expr_name]], "counts")[match(names(gene_eff_vec), rownames(expr_list[[expr_name]])), which(cell_anno$is_target)] %>% 
        set_colnames(cell_anno$cellid[cell_anno$is_target])
      sub_mat <- eff_mat[, which(target_cell_list %in% perturbed_cell_list)]
      sub_mat <- perturb_count_matrix(sub_mat, gene_eff_vec)
      eff_mat[, which(target_cell_list %in% perturbed_cell_list)] <- sub_mat
      write.table(as.matrix(eff_mat), file = paste0(perturbed_expr_dir, "/",cr_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

#perturbed matrix: perturbed cells are all perturbed with cell type-specific genes 
map2(vary_cr_cell_anno, names(vary_cr_cell_anno), ~{
  cr_name <- .y
  dir.create(paste0(perturbed_expr_dir_all_cells, "/",cr_name), showWarnings = FALSE)
  map2(.x, names(.x), ~{
    cell_anno <- .x
    target_cell_list <- filter(cell_anno, is_target)$cellid
    perturbed_cell_list <- filter(cell_anno, is_perturbed)$cellid
    expr_name <- .y
    map2(vary_cr_gene_anno, names(vary_cr_gene_anno), ~{
      ct_specific_gene_list <- filter(.x, is_ct_specific) %>% pull(mmu_symbol)
      ct_specific_gene_eff_vec <- rep(2^0.5, length(ct_specific_gene_list)) %>% set_names(ct_specific_gene_list)
      causal_gene_list <- filter(.x, is_causal) %>% pull(mmu_symbol)
      causal_gene_eff_vec <- rep(2^0.5, length(causal_gene_list)) %>% set_names(causal_gene_list)
      all_gene_list <-filter(.x, is_ct_specific|is_causal) %>% pull(mmu_symbol)
      gs_name <- .y
      #cell type-specific effect
      ct_mat <- assay(expr_list[[expr_name]], "counts")[match(ct_specific_gene_list, rownames(expr_list[[expr_name]])), which(cell_anno$is_target)] %>% 
        set_colnames(cell_anno$cellid[cell_anno$is_target])
      ct_mat <- perturb_count_matrix(ct_mat, ct_specific_gene_eff_vec)
      #get the original matrix that's used for disease gene perturbation
      sub_mat <-assay(expr_list[[expr_name]], "counts")[match(causal_gene_list, rownames(expr_list[[expr_name]])), which(cell_anno$is_target)] %>% 
        set_colnames(cell_anno$cellid[cell_anno$is_target])
      eff_mat <- sub_mat[,which(colnames(sub_mat) %in% target_cell_list)]
      eff_mat <- perturb_count_matrix(eff_mat, causal_gene_eff_vec)
      sub_mat[,which(colnames(sub_mat) %in% target_cell_list)] <- eff_mat
      #combine matrix and print output
      out_mat <- rbind(ct_mat, sub_mat) %>% .[match(all_gene_list, rownames(.)),]
      write.table(as.matrix(out_mat), file = paste0(perturbed_expr_dir_all_cells, "/",cr_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

## write out parameter df 
vary_cr_para_df <- expand_grid(cr_name = names(cell_ratio),
                               gs_name = names(z_score_list),
                               expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir, "/",cr_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir, "/", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", cr_name,".",expr_name, ".cell_anno.txt"))

vary_cr_para_df_all_cells <- expand_grid(cr_name = names(cell_ratio),
                               gs_name = names(z_score_list),
                               expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir_all_cells, "/",cr_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir, "/", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", cr_name,".",expr_name, ".cell_anno.txt"))

#
write.table(vary_cr_para_df, file = paste0(perturbed_expr_dir, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(vary_cr_para_df_all_cells, file = paste0(perturbed_expr_dir_all_cells, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)

##### 4. Multiple cell types #####
gene_anno_dir_multi <- here("data","gwas","causal_sim","multi_cell_types","multi_gene_anno")
gene_anno_dir_multi_cor <- here("data","gwas","causal_sim","multi_cell_types","multi_cor_gene_anno")
gene_anno_dir_multi_assoc <- here("data","gwas","causal_sim","multi_cell_types","multi_assoc_gene_anno")

cell_anno_dir <- here("data","expr","causal_sim","multi_cell_types","cell_anno")

perturbed_expr_dir_multi <- here("data","expr","causal_sim","multi_cell_types","multi")
perturbed_expr_dir_multi_cor <- here("data","expr","causal_sim","multi_cell_types","multi_cor")
perturbed_expr_dir_multi_assoc <- here("data","expr","causal_sim","multi_cell_types","multi_assoc")

set.seed(100)
multi_gene_anno <- z_score_list %>%
  map(~mutate(.x, may_be_causal = ifelse(ZSTAT>0 & 1:n() <= 1000 , T, F), may_be_ct_specific = ifelse(ZSTAT>0 & 1:n() > 1000 , T, F))) %>%
  map(~mutate(.x, is_causal = ifelse(mmu_symbol %in% sample(filter(., may_be_causal)$mmu_symbol, 250), T, F))) %>%
  map(~mutate(.x, is_ct_specific = ifelse(mmu_symbol %in% sample(filter(., may_be_ct_specific)$mmu_symbol, 750), T, F))) 

multi_cor_gene_anno <- multi_gene_anno %>% 
  map(~mutate(.x, is_causal_2 = ifelse(mmu_symbol %in% sample(filter(., may_be_causal & (!is_causal))$mmu_symbol, 250), T, F))) %>%
  map(~mutate(.x, is_causal_3 = ifelse(mmu_symbol %in% sample(filter(., may_be_causal & (!is_causal) & (!is_causal_2))$mmu_symbol, 250), T, F))) 
  
multi_assoc_gene_anno <- multi_gene_anno %>% 
  map(~mutate(.x, is_ct_specific_2 = ifelse(mmu_symbol %in% sample(filter(., may_be_ct_specific & (!is_ct_specific))$mmu_symbol, 750), T, F))) %>%
  map(~mutate(.x, is_ct_specific_3 = ifelse(mmu_symbol %in% sample(filter(., may_be_ct_specific & (!is_ct_specific) & (!is_ct_specific_2))$mmu_symbol, 750), T, F))) 

#write out
map2(multi_gene_anno, names(multi_gene_anno), ~write.table(.x, file= paste0(gene_anno_dir_multi, "/", .y,".gene_anno.txt"), quote = F,row.names = F))
map2(multi_cor_gene_anno, names(multi_cor_gene_anno), ~write.table(.x, file= paste0(gene_anno_dir_multi_cor, "/", .y,".gene_anno.txt"), quote = F,row.names = F))
map2(multi_assoc_gene_anno, names(multi_assoc_gene_anno), ~write.table(.x, file= paste0(gene_anno_dir_multi_assoc, "/", .y,".gene_anno.txt"), quote = F,row.names = F))

##sample random cells as target cell types
set.seed(98)
multi_cell_anno <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map(~mutate(.x, is_target = ifelse(1:n() %in% sample(n(), 100), T, F))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(is_target, "target_cell_type", cell_ontology_class))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(cellid %in% sample(filter(.x, new_cell_ontology_class != "target_cell_type") %>% pull(cellid), 100), "target_cell_type_2", new_cell_ontology_class))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(cellid %in% sample(filter(.x, !new_cell_ontology_class %in% c("target_cell_type", "target_cell_type_2")) %>% pull(cellid), 100), "target_cell_type_3", new_cell_ontology_class))) %>%
  map(~mutate(.x, is_perturbed = ifelse(new_cell_ontology_class %in% c("target_cell_type", "target_cell_type_2", "target_cell_type_3"), TRUE, FALSE)))

#write out gene annotation table and cell annotation table
map2(multi_cell_anno, names(multi_cell_anno), ~write.table(.x, file = paste0(cell_anno_dir, "/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))

### perturb expression
effect_size = seq(0.1, 1, 0.1) %>% set_names(paste0("es_", format(.,digits = 1)))

#multiple cell types
map2(effect_size, names(effect_size), ~{
  es <- .x
  es_name <- .y
  dir.create(paste0(perturbed_expr_dir_multi, "/",es_name), showWarnings = FALSE)
  map2(multi_gene_anno, names(multi_gene_anno), ~{
    gene_list <- filter(.x, is_causal | is_ct_specific) %>% pull(mmu_symbol)
    gene_eff_vec <- rep(2^es, length(gene_list)) %>% set_names(gene_list)
    gs_name <- .y
    map2(multi_cell_anno, names(multi_cell_anno), ~{
      eff_mat <- assay(expr_list[[.y]], "counts")[match(names(gene_eff_vec), rownames(expr_list[[.y]])), which(.x$is_perturbed)] %>% 
        set_colnames(.x$cellid[which(.x$is_perturbed)])
      out_mat <- perturb_count_matrix(eff_mat, gene_eff_vec)
      write.table(as.matrix(out_mat), file = paste0(perturbed_expr_dir_multi, "/",es_name, "/", gs_name,".",.y,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})


#multiple correlated cell types
map2(effect_size, names(effect_size), ~{
  es <- .x
  es_name <- .y
  dir.create(paste0(perturbed_expr_dir_multi_cor, "/",es_name), showWarnings = FALSE)
  map2(multi_cor_gene_anno, names(multi_cor_gene_anno), ~{
    #cell type specific genes 
    ct_specific_gene_list <- filter(.x, is_ct_specific) %>% pull(mmu_symbol)
    ct_specific_gene_eff_vec <- rep(2^0.5, length(ct_specific_gene_list)) %>% set_names(ct_specific_gene_list)
    #causal genes
    causal_gene_list <- filter(.x, is_causal) %>% pull(mmu_symbol)
    causal_gene_list_2 <- filter(.x, is_causal_2) %>% pull(mmu_symbol)
    causal_gene_list_3 <- filter(.x, is_causal_3) %>% pull(mmu_symbol)
    
    causal_gene_eff_vec <- rep(2^0.5, length(causal_gene_list)) %>% set_names(causal_gene_list)
    causal_gene_eff_vec_2 <- rep(2^0.5, length(causal_gene_list_2)) %>% set_names(causal_gene_list_2)
    causal_gene_eff_vec_3 <- rep(2^0.5, length(causal_gene_list_3)) %>% set_names(causal_gene_list_3)
    gs_name <- .y
    map2(multi_cell_anno, names(multi_cell_anno), ~{
      #cell list
      perturbed_cell_list = .x$cellid[which(.x$is_perturbed)]
      target_cell_list = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type")]
      target_cell_list_2 = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type_2")]
      target_cell_list_3 = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type_3")]
      
      all_mat <- assay(expr_list[[.y]], "counts")[match(c(causal_gene_list, causal_gene_list_2,causal_gene_list_3,ct_specific_gene_list), rownames(expr_list[[.y]])), which(.x$is_perturbed)] %>% 
        set_colnames(perturbed_cell_list)
      
      #cell type specific
      ct_mat <- perturb_count_matrix(all_mat[match(ct_specific_gene_list, rownames(all_mat)),], ct_specific_gene_eff_vec)
      all_mat[match(ct_specific_gene_list, rownames(all_mat)),] <- ct_mat
      
      #disease perturbation
      sub_mat <- perturb_count_matrix(all_mat[match(causal_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list)], causal_gene_eff_vec)
      sub_mat_2 <- perturb_count_matrix(all_mat[match(causal_gene_list_2, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_2)], causal_gene_eff_vec_2)
      sub_mat_3 <- perturb_count_matrix(all_mat[match(causal_gene_list_3, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_3)], causal_gene_eff_vec_3)
      
      all_mat[match(causal_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list)] <- sub_mat
      all_mat[match(causal_gene_list_2, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_2)] <- sub_mat_2
      all_mat[match(causal_gene_list_2, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_3)] <- sub_mat_3
      
      write.table(as.matrix(all_mat), file = paste0(perturbed_expr_dir_multi_cor, "/",es_name, "/", gs_name,".",.y,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

#multiple associated cell types - disease genes are the same 
map2(effect_size, names(effect_size), ~{
  es <- .x
  es_name <- .y
  dir.create(paste0(perturbed_expr_dir_multi_assoc, "/",es_name), showWarnings = FALSE)
  map2(multi_assoc_gene_anno, names(multi_assoc_gene_anno), ~{
    #cell type specific genes 
    ct_specific_gene_list <- filter(.x, is_ct_specific) %>% pull(mmu_symbol)
    ct_specific_gene_list_2 <- filter(.x, is_ct_specific) %>% pull(mmu_symbol)
    ct_specific_gene_list_3 <- filter(.x, is_ct_specific) %>% pull(mmu_symbol)
    ct_specific_gene_eff_vec <- rep(2^0.5, length(ct_specific_gene_list)) %>% set_names(ct_specific_gene_list)
    ct_specific_gene_eff_vec_2 <- rep(2^0.5, length(ct_specific_gene_list_2)) %>% set_names(ct_specific_gene_list_2)
    ct_specific_gene_eff_vec_3 <- rep(2^0.5, length(ct_specific_gene_list_3)) %>% set_names(ct_specific_gene_list_3)
    #causal genes
    causal_gene_list <- filter(.x, is_causal) %>% pull(mmu_symbol)
    causal_gene_eff_vec <- rep(2^0.5, length(causal_gene_list)) %>% set_names(causal_gene_list)
    
    gs_name <- .y
    map2(multi_cell_anno, names(multi_cell_anno), ~{
      #cell list
      perturbed_cell_list = .x$cellid[which(.x$is_perturbed)]
      target_cell_list = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type")]
      target_cell_list_2 = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type_2")]
      target_cell_list_3 = .x$cellid[which(.x$new_cell_ontology_class == "target_cell_type_3")]
      
      all_mat <- assay(expr_list[[.y]], "counts")[match(c(causal_gene_list, ct_specific_gene_list, ct_specific_gene_list_2, ct_specific_gene_list_3), rownames(expr_list[[.y]])), which(.x$is_perturbed)] %>% 
        set_colnames(perturbed_cell_list) %>%
        as.matrix()
      
      #cell type specific
      ct_mat <- perturb_count_matrix(all_mat[match(ct_specific_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list)], ct_specific_gene_eff_vec)
      ct_mat_2 <- perturb_count_matrix(all_mat[match(ct_specific_gene_list_2, rownames(all_mat)),which(colnames(all_mat) %in% target_cell_list_2)], ct_specific_gene_eff_vec_2)
      ct_mat_3 <- perturb_count_matrix(all_mat[match(ct_specific_gene_list_3, rownames(all_mat)),which(colnames(all_mat) %in% target_cell_list_3)], ct_specific_gene_eff_vec_3)
      all_mat[match(ct_specific_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list)] <- ct_mat
      all_mat[match(ct_specific_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_2)] <- ct_mat
      all_mat[match(ct_specific_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% target_cell_list_3)] <- ct_mat
      
      #disease perturbation
      sub_mat <- perturb_count_matrix(all_mat[match(causal_gene_list, rownames(all_mat)), which(colnames(all_mat) %in% perturbed_cell_list)], causal_gene_eff_vec)
      all_mat[match(causal_gene_list, rownames(all_mat)),] <- sub_mat
      
      write.table(as.matrix(all_mat), file = paste0(perturbed_expr_dir_multi_assoc, "/",es_name, "/", gs_name,".",.y,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

#write out parameter data frame
## write out parameter df 
multi_para_df <- expand_grid(es_name = names(effect_size),
                                gs_name = names(z_score_list),
                                expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir_multi, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir_multi, "/", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", expr_name, ".cell_anno.txt"))

multi_cor_para_df <- expand_grid(es_name = names(effect_size),
                                        gs_name = names(z_score_list),
                                        expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir_multi, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir_multi, "/", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", expr_name, ".cell_anno.txt"))

multi_assoc_para_df <- expand_grid(es_name = names(effect_size),
                                 gs_name = names(z_score_list),
                                 expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(perturbed_expr_dir_multi, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(gene_anno_dir_multi, "/", gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(cell_anno_dir, "/", expr_name, ".cell_anno.txt"))

#
write.table(multi_para_df, file = paste0(perturbed_expr_dir_multi, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(multi_cor_para_df , file = paste0(perturbed_expr_dir_multi_cor, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(multi_assoc_para_df , file = paste0(perturbed_expr_dir_multi_assoc, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)


##### 5. B cells perturbation #####

#### 6. Large effect ####
##### Varying number of effect genes ####
library("seismicGWAS")
##test
# expr_name = "expr_ds_6"
example_sce = expr_list[[expr_name]]
counts_mat = assay(example_sce, "counts")

# gl_tbl = z_score_list$gs_6 %>% filter(mmu_symbol %in% rownames(t)) %>% arrange(-ZSTAT) %>% dplyr::slice(1:250) 
# gl = gl_tbl %>% pull(mmu_symbol)
# replace_mat = as.matrix(t[match(gl, rownames(t)),])
replace_mat = as.matrix(out_mat)

#replace_mat = as.matrix(counts_mat[match(rownames(replace_mat), rownames(counts_mat)), match(colnames(replace_mat), colnames(counts_mat))]) 
# gs_name = "gs_4"
example_magma = paste0("/grain/ql29/seismic-analysis/data/gwas/causal_sim/zscore/",gs_name,".genes.out")
example_sce$cell_ontology_class[example_sce$cellid %in% colnames(replace_mat)] = "target_cell_type"

counts_mat = counts_mat %>% as.matrix()
size_factor = colSums(counts_mat) / colSums(2^assay(example_sce, "logcounts") -1) 

row_indices <- match(rownames(replace_mat), rownames(counts_mat))
col_indices <- which(example_sce$cell_ontology_class == "target_cell_type")

counts_mat[row_indices, col_indices] = replace_mat
counts_mat <- as(counts_mat, "dgCMatrix")

logcounts_mat <- sweep_sparse(counts_mat, margin = 2, stats = size_factor) %>% transform_sparse(function(x) log2(x+1))
logcpm_mat <- sweep_sparse(counts_mat*1e6, margin = 2, stats = colSums(counts_mat)) %>% transform_sparse(function(x) log2(x+1))

assay(example_sce, "counts") = as(counts_mat, "dgCMatrix")
assay(example_sce, "logcounts") = as(logcounts_mat,"dgCMatrix")
assay(example_sce, "logcpm") = as(logcpm_mat, "dgCMatrix")


# 
# counts_mat[row_indices, col_indices] <- as.matrix(replace_mat) 
# cpm_mat <- sweep(counts_mat*1e6, MARGIN=2,STATS=colSums(counts_mat),FUN="/")
# sf <- colSums(assay(example_sce, "counts"))/colSums(2^assay(example_sce, "logcounts") - 1)
# logcounts_mat <- log2(sweep(counts_mat, MARGIN = 2, STATS = sf, FUN = "/") + 1)
# 
# assay(example_sce, "counts") = counts_mat
# assay(example_sce, "cpm") <- as(cpm_mat, "dgCMatrix")
# assay(example_sce, "logcpm") <- as(log2(cpm_mat + 1), "dgCMatrix")

# 
example_sscore <- calc_specificity(example_sce, assay_name = "logcounts", ct_label_col = "cell_ontology_class")
example_sscore_hsa <- translate_gene_ids(example_sscore, from = "mmu_symbol")
example_association <- get_ct_trait_associations(sscore = example_sscore_hsa, magma = example_magma)
example_inf_genes <- find_inf_genes("target_cell_type", example_sscore_hsa, example_magma)
example_inf_genes <- example_inf_genes %>% left_join(example_magma %>% mutate(GENE = as.character(GENE)), by=c("gene"="GENE"))

