# script to generate data for causal simulation

if (!require("here")) {
  install.packages("here")
  library("here")
}
if (!require("magrittr")) {
  install.packages("magrittr")
  library("magrittr")
}
if(!require("tidyverse")) {
  install.packages("tidyverse")
  library("tidyverse")
}
if (!require("SingleCellExperiment")) {
  if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
  }
  BiocManager::install("SingleCellExperiment")
  library("SingleCellExperiment")
} 
if (!require("scDesign3", quietly = TRUE)) {
  if(!requireNamespace("devtools")){
    install.packages("devtools")
  }
  devtools::install_github("SONGDONGYUAN1994/scDesign3")
  library("scDesign3")
}

# load additional functions
source(here("src", "tools", "sparse_mat_util.R"))
source(here("src", "tools", "munge_sce_mat.R"))

# load mmu_hsa_mapping
load(here("data","ref","mapping","mmu_hsa_mapping.rda"))

# load random gene sets generated by null_sum_all.sh
zscore_dir <- here("data", "causal_sim", "zscore")
scdrs_dir <- here("data", "causal_sim", "scdrs_gs")
magma_raw_dir <- here("data", "causal_sim", "magma_raw")
expr_dir <- here("data", "null_sim", "expr_rda_rs")
h5ad_dir <- here("data", "null_sim", "expr_h5ad_rs")

# load all random gene sets generated
z_score_list <- list.files(zscore_dir) %>%
  set_names(gsub(pattern = ".genes.out", replacement = "", x = ., fixed = T)) %>%
  map(~read.table(file=paste0(zscore_dir,"/",.x), header = T)) %>%
  map(~left_join(.x, distinct(mmu_hsa_mapping, hsa_entrez, mmu_symbol), by = c("GENE"="hsa_entrez")))

# load expression data
expr_list <- list.files(expr_dir) %>%
  set_names(gsub(pattern = ".rda", replacement = "", x = ., fixed = T)) %>%
  map(~ {load(paste0(expr_dir,"/",.x)); return(sce)}) %>%
  map(~ {colnames(.x) <- .x$cellid; .x})

# keep genes in original expression data sets
z_score_list <- z_score_list %>%
  map(~mutate(.x, in_expr = ifelse(mmu_symbol %in% rownames(expr_list$expr_ds_1), T, F))) %>%
  map(~filter(.x, in_expr)) %>% 
  map(~group_by(.x, mmu_symbol)) %>%
  map(~mutate(.x, ZSTAT = mean(ZSTAT))) %>%
  map(~ungroup(.x)) %>%
  map(~distinct(.x,mmu_symbol, .keep_all = T)) %>%
  map(~arrange(.x, -ZSTAT)) 


# function definition for scDesign3 data generation
perturb_count_matrix <- function(sce, covar_df, cellids, geneids, effect_size_para, copula_para_list, para_list) {
  gene_idx <- match(geneids, rownames(sce))
  gene_loc <- match(geneids, colnames(copula_para_list$`1`))
  cell_idx <- match(cellids, colnames(sce))
  covar_df <- dplyr::slice(covar_df, cell_idx)
  new_count_mat <- simu_new(
    sce = sce[gene_idx, cell_idx],
    mean_mat = para_list$mean_mat[cell_idx, gene_idx] %>% sweep(MARGIN = 1, STATS = effect_size_para, FUN = "*"),
    sigma_mat = para_list$sigma_mat[cell_idx, gene_idx],
    zero_mat = para_list$zero_mat[cell_idx, gene_idx],
    quantile_mat = NULL,
    copula_list = list("1" = copula_para_list$`1`[gene_loc, gene_loc]),
    n_cores = 10,
    family_use = "nb",
    input_data = mutate(covar_df, corr_group = 1),
    new_covariate = covar_df,
    important_feature = "all",
    filtered_gene = NULL
  )
  return(new_count_mat)
}

# Synthetic data generation: 1 cell type
sc3_gene_anno_dir <- here("data", "causal_sim", "sc3_standard", "gene_anno")
sc3_cell_anno_dir <- here("data", "causal_sim", "standard_scdesign3_model")
sc3_perturbed_expr_dir <- here("data", "causal_sim", "sc3_standard", "perturbed_expr")

# load fitted scDesign3 model
load(here("data", "causal_sim", "standard_scdesign3_model", "sc_para_list.rda"))

# list all previously saved cell annotation
cell_anno_all <- list.files(sc3_cell_anno_dir, pattern = "cell_anno.txt", full.names = T) %>%
  set_names(str_extract(., pattern = "expr_ds_[0-9]*")) %>%
  map(~read.table(.x, header = T, sep="\t")) %>%
  map(~as_tibble(.x)) 

# sanity check: if the cell id matches the expression dataset
map2(cell_anno_all, expr_list, ~filter(.x, cellid %in% colnames(.y))) %>%
  map(~nrow(.x))

# add library size annotation
cell_anno_all <- cell_anno_all %>%
  map2(expr_list, ~mutate(.x, library_size = colSums(assay(.y,"counts")))) 

# sample random gene sets - get genes with certain expression and correct scdesign3 parameter
candidate_gene_list <- map(expr_list, ~assay(.x, "counts") > 0) %>%
  map(~rowSums(.x)) %>%
  map(~names(which(.x > 10))) %>%
  map2(names(.), ~intersect(.x, colnames(sc_para_list[[.y]]$para$mean_mat)[colSums(sc_para_list[[.y]]$para$mean_mat)<1e20])) 

# make gene annotation
gene_anno_all <- map(candidate_gene_list, ~ {
  gl <- .x
  map(z_score_list, ~mutate(.x, in_perturb_list = ifelse(mmu_symbol %in% gl & in_expr, TRUE, FALSE)))}) %>%
  map(~map(.x, ~filter(.x, in_perturb_list))) %>%
  map(~map(.x, ~arrange(.x,-ZSTAT)))

# gene weights
gene_weight <- gene_anno_all %>%
  map(~map(.x, ~ {
    gene_pos_zscore <- filter(.x, ZSTAT > 0)
    pull(gene_pos_zscore, ZSTAT) %>% set_names(pull(gene_pos_zscore, mmu_symbol))
  }))

# sample genes
set.seed(100)
gene_anno <- c(0.2,  0.4, 0.5, 0.6, 0.8) %>%
  set_names(c("gr_0.2","gr_0.4","gr_0.5", "gr_0.6", "gr_0.8")) %>%
  map(~ {
    gr<- .x
    map2(gene_anno_all, gene_weight , ~map2(.x,.y, ~mutate(.x,  is_causal = ifelse(mmu_symbol %in% sample(names(.y), gr*1000, prob = .y), T, F)))) %>%
      map(~map(.x, ~mutate(.x, is_ct_specific = ifelse(mmu_symbol %in% sample(filter(.x, !is_causal)$mmu_symbol, 1000 - gr*1000), T, F))))}) 

# write out gene tables
map2(gene_anno, names(gene_anno), ~ {
  gr <- .y
  map2(.x,names(.x), ~ {
    expr_name <- .y
    map2(.x, names(.x), ~ {
      if (! file.exists( paste0(sc3_gene_anno_dir, "/",gr,".",expr_name,".", .y,".gene_anno.txt"))) {
        write.table(.x, file= paste0(sc3_gene_anno_dir, "/",gr,".",expr_name,".", .y,".gene_anno.txt"), quote = F,row.names = F)
      }} )
  })})


# perturb expression
set.seed(123)
effect_size = c(0.05, 0.1, 0.5, 1, 2, 5) %>% set_names(c("es_0.05", "es_0.1", "es_0.5","es_1.0","es_2.0","es_5.0"))

map2(gene_anno, names(gene_anno), ~ {
  gene_anno_list <- .x
  gr_name <- .y
  print(gr_name)
  dir.create(paste0(sc3_perturbed_expr_dir, "/",gr_name), showWarnings = FALSE)
  map2(effect_size, names(effect_size), ~ {
    es <- .x
    es_name <- .y
    dir.create(paste0(sc3_perturbed_expr_dir, "/",gr_name, "/",es_name), showWarnings = FALSE)
    
    map2(gene_anno_list, names(gene_anno_list), ~ {
      expr_name <- .y
      sce <- expr_list[[expr_name]]
      cell_anno_tbl = cell_anno_all[[expr_name]]
      map2(.x, names(.x), ~ {
        gs_name <- .y
        coldata_df <-  cell_anno_tbl %>% as.data.frame() %>% set_rownames(.$cellid) %>% select(cell_ontology_class, library_size)
        gene_list <- filter(.x, is_causal | is_ct_specific) %>% pull(mmu_symbol)
        cell_list <- cell_anno_tbl$cellid[cell_anno_tbl$is_target]         
        out_mat <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list, geneids = gene_list,
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula$copula_list, para_list = sc_para_list[[expr_name]]$para)
        
        write.table(as.matrix(out_mat), file = paste0(sc3_perturbed_expr_dir,"/", gr_name, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
      })
    })
  })
})



sc3_output_dir<- here("results", "causal_sim", "sc3_standard") 

sc3_para_df <- expand_grid(gr_name = names(gene_anno), 
                           es_name = names(effect_size), 
                           gs_name = names(z_score_list), 
                           expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(sc3_perturbed_expr_dir,"/", gr_name,"/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(sc3_gene_anno_dir, "/",gr_name,".", expr_name,".",gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(sc3_cell_anno_dir, "/", expr_name, ".cell_anno.txt"),
         output_header = paste0(sc3_output_dir, "/", gr_name, "/", es_name, "/",gs_name,".",expr_name))

write.table(sc3_para_df, file = paste0(sc3_perturbed_expr_dir, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)


# try multiple cell types
sc3_multi_ct_gene_anno_dir_random <- here("data", "causal_sim","sc3_multi_ct","random","gene_anno")
sc3_multi_ct_gene_anno_dir_no_overlap <- here("data", "causal_sim","sc3_multi_ct","no_overlap","gene_anno")
sc3_multi_ct_gene_anno_dir_ct_overlap <- here("data", "causal_sim","sc3_multi_ct","ct_overlap","gene_anno")
sc3_multi_ct_gene_anno_dir_causal_overlap <- here("data", "causal_sim","sc3_multi_ct","causal_overlap","gene_anno")
sc3_multi_ct_cell_anno_dir <- here("data", "causal_sim", "multi_ct_scdesign3_model")
sc3_multi_ct_perturbed_expr_dir_random <- here("data", "causal_sim", "sc3_multi_ct","random","perturbed_expr")
sc3_multi_ct_perturbed_expr_dir_no_overlap <- here("data", "causal_sim", "sc3_multi_ct","no_overlap","perturbed_expr")
sc3_multi_ct_perturbed_expr_dir_ct_overlap <- here("data", "causal_sim","sc3_multi_ct","ct_overlap","perturbed_expr")
sc3_multi_ct_perturbed_expr_dir_causal_overlap <- here("data", "causal_sim","sc3_multi_ct","causal_overlap","perturbed_expr")

# sample random cells as target cell types
multi_ct_cell_anno <- list.files(sc3_multi_ct_cell_anno_dir , pattern = "cell_anno.txt", full.names = T) %>%
  set_names(str_extract(., pattern = "expr_ds_[0-9]*")) %>%
  map(~read.table(.x, header = T, sep="\t")) %>%
  map(~as_tibble(.x)) 

load(here("data", "causal_sim", "multi_ct_scdesign3_model", "sc_para_list.rda"))

# sample random gene sets - get genes with certain expression and correct scdesign3 parameter
multi_ct_candidate_gene_list <- map(expr_list, ~assay(.x, "counts") > 0) %>%
  map(~rowSums(.x)) %>%
  map(~names(which(.x > 10))) %>%
  map2(names(.), ~intersect(.x, colnames(sc_para_list[[.y]]$para$mean_mat)[colSums(sc_para_list[[.y]]$para$mean_mat)<1e20] ))

# process gene annotation
multi_ct_gene_anno_all <- map(multi_ct_candidate_gene_list, ~ {
  gl <- .x
  map(z_score_list, ~mutate(.x, in_perturb_list = ifelse(mmu_symbol %in% gl & in_expr, TRUE, FALSE)))
}) %>%
  map(~map(.x, ~filter(.x, in_perturb_list))) %>%
  map(~map(.x, ~arrange(.x,-ZSTAT))) 

# gene weight
multi_cell_gene_weight <- multi_ct_gene_anno_all %>%
  map(~map(.x, ~ {
    gene_pos_zscore <- filter(.x, ZSTAT > 0)
    pull(gene_pos_zscore, ZSTAT) %>% set_names(pull(gene_pos_zscore, mmu_symbol))
  }))

# sample genes
set.seed(100)
multi_ct_gene_anno_random = multi_ct_gene_anno_all %>%
  map2(multi_cell_gene_weight, ~map2(.x,.y, ~mutate(.x,  is_causal_1 = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map2(multi_cell_gene_weight, ~map2(.x,.y, ~mutate(.x,  is_causal_2 = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map2(multi_cell_gene_weight, ~map2(.x,.y, ~mutate(.x,  is_causal_3 = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_1 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_1)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_2 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_2)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_3 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_3)$mmu_symbol, 500), T, F))))

# sample genes exclusively 
multi_ct_gene_anno_no_overlap = multi_ct_gene_anno_all %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~mutate(.x,  is_causal_1 = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~ {gl <- .y[names(.y) %in% pull(filter(.x, !is_causal_1), mmu_symbol)]; mutate(.x,  is_causal_2 = ifelse(mmu_symbol %in% sample(names(gl), 500, prob = gl), T, F))})) %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~ {gl <- .y[names(.y) %in% pull(filter(.x, !is_causal_1 & !is_causal_2), mmu_symbol)]; mutate(.x,  is_causal_3 = ifelse(mmu_symbol %in% sample(names(gl), 500, prob = gl), T, F))})) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_1 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_1 & !is_causal_2 & !is_causal_3)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_2 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_1 & !is_causal_2 & !is_causal_3 & !is_ct_specific_1)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_3 = ifelse(mmu_symbol %in% sample(filter(., !is_causal_1 & !is_causal_2 & !is_causal_3 & !is_ct_specific_1 & !is_ct_specific_2)$mmu_symbol, 500), T, F)))) 

# sample genes with shared other genes
multi_ct_gene_anno_ct_overlap = multi_ct_gene_anno_all %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~mutate(.x,  is_causal_1 = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~ {gl <- .y[names(.y) %in% pull(filter(.x, !is_causal_1), mmu_symbol)]; mutate(.x,  is_causal_2 = ifelse(mmu_symbol %in% sample(names(gl), 500, prob = gl), T, F))})) %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~ {gl <- .y[names(.y) %in% pull(filter(.x, !is_causal_1 & !is_causal_2), mmu_symbol)]; mutate(.x,  is_causal_3 = ifelse(mmu_symbol %in% sample(names(gl), 500, prob = gl), T, F))})) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific = ifelse(mmu_symbol %in% sample(filter(., !is_causal_1 & !is_causal_2 & !is_causal_3)$mmu_symbol, 500), T, F)))) 

# sample genes with shared causal genes
multi_ct_gene_anno_causal_overlap = multi_ct_gene_anno_all %>%
  map2(multi_cell_gene_weight , ~map2(.x,.y, ~mutate(.x,  is_causal = ifelse(mmu_symbol %in% sample(names(.y), 500, prob = .y), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_1 = ifelse(mmu_symbol %in% sample(filter(., !is_causal)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_2 = ifelse(mmu_symbol %in% sample(filter(., !is_causal & !is_ct_specific_1)$mmu_symbol, 500), T, F)))) %>%
  map(~map(.x, ~mutate(.x,  is_ct_specific_3 = ifelse(mmu_symbol %in% sample(filter(., !is_causal & !is_ct_specific_1 & !is_ct_specific_2)$mmu_symbol, 500), T, F)))) 


# write out gene tables
map2(multi_ct_gene_anno_random, names(multi_ct_gene_anno_random), ~ {
  gs_name <- .y
  map2(.x,names(.x), ~write.table(.x,file= paste0(sc3_multi_ct_gene_anno_dir_random, "/",gs_name,".", .y,".gene_anno.txt"), quote = F,row.names = F))})

map2(multi_ct_gene_anno_no_overlap, names(multi_ct_gene_anno_no_overlap), ~ {
  gs_name <- .y
  map2(.x,names(.x), ~write.table(.x,file= paste0(sc3_multi_ct_gene_anno_dir_no_overlap, "/",gs_name,".", .y,".gene_anno.txt"), quote = F,row.names = F))})

map2(multi_ct_gene_anno_ct_overlap, names(multi_ct_gene_anno_ct_overlap), ~ {
  gs_name <- .y
  map2(.x,names(.x), ~write.table(.x,file= paste0(sc3_multi_ct_gene_anno_dir_ct_overlap, "/",gs_name,".", .y,".gene_anno.txt"), quote = F,row.names = F))})

map2(multi_ct_gene_anno_causal_overlap, names(multi_ct_gene_anno_causal_overlap), ~ {
  gs_name <- .y
  map2(.x,names(.x), ~write.table(.x,file= paste0(sc3_multi_ct_gene_anno_dir_causal_overlap, "/",gs_name,".", .y,".gene_anno.txt"), quote = F,row.names = F))})

# perturb expression
effect_size = c(0.05, 0.1, 0.5, 1, 2, 5) %>% set_names(c("es_0.05", "es_0.1", "es_0.5","es_1.0","es_2.0","es_5.0"))

# perturb
set.seed(123)
map2(effect_size, names(effect_size), ~ {
  es <- .x
  es_name <- .y
  dir.create(paste0(sc3_multi_ct_perturbed_expr_dir_random, "/",es_name), showWarnings = FALSE)
  
  map2(multi_ct_gene_anno_random, names(multi_ct_gene_anno_random), ~ {
    expr_name <- .y
    sce <- expr_list[[expr_name]]
    coldata_df <- multi_ct_cell_anno[[expr_name]] %>% as.data.frame() %>% set_rownames(.$cellid) %>% select(new_cell_ontology_class, library_size) %>% set_colnames(c("cell_ontology_class","library_size"))
    map2(.x, names(.x), ~ {
      gs_name <- .y
    
      gene_list_1 <- filter(.x, is_causal_1 | is_ct_specific_1) %>% pull(mmu_symbol)
      gene_list_2 <- filter(.x, is_causal_2 | is_ct_specific_2) %>% pull(mmu_symbol)
      gene_list_3 <- filter(.x, is_causal_3 | is_ct_specific_3) %>% pull(mmu_symbol)
      
      cell_list_1 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_1"]
      cell_list_2 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_2"]
      cell_list_3 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_3"]
      
      out_mat_1 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_1, geneids = gene_list_1, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_2 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_2, geneids = gene_list_2, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_3 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_3, geneids = gene_list_3, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      
      aux_mat <- assay(sce,"counts")[match(unique(c(gene_list_1,gene_list_2,gene_list_3)), rownames(sce)), match(c(cell_list_1, cell_list_2, cell_list_3), colnames(sce))] %>% as.matrix()
      
      aux_mat[match(gene_list_1, rownames(aux_mat)), match(cell_list_1, colnames(aux_mat))] <- out_mat_1
      aux_mat[match(gene_list_2, rownames(aux_mat)), match(cell_list_2, colnames(aux_mat))] <- out_mat_2
      aux_mat[match(gene_list_3, rownames(aux_mat)), match(cell_list_3, colnames(aux_mat))] <- out_mat_3
      
      write.table(as.matrix(aux_mat), file = paste0(sc3_multi_ct_perturbed_expr_dir_random, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})


set.seed(456)
map2(effect_size, names(effect_size), ~ {
  es <- .x
  es_name <- .y
  dir.create(paste0(sc3_multi_ct_perturbed_expr_dir_no_overlap, "/",es_name), showWarnings = FALSE)
  
  map2(multi_ct_gene_anno_no_overlap, names(multi_ct_gene_anno_no_overlap), ~ {
    expr_name <- .y
    sce <- expr_list[[expr_name]]
    coldata_df <- multi_ct_cell_anno[[expr_name]] %>% as.data.frame() %>% set_rownames(.$cellid) %>% select(new_cell_ontology_class, library_size) %>% set_colnames(c("cell_ontology_class","library_size"))
    map2(.x, names(.x), ~ {
      gs_name <- .y
      
      gene_list_1 <- filter(.x, is_causal_1 | is_ct_specific_1) %>% pull(mmu_symbol)
      gene_list_2 <- filter(.x, is_causal_2 | is_ct_specific_2) %>% pull(mmu_symbol)
      gene_list_3 <- filter(.x, is_causal_3 | is_ct_specific_3) %>% pull(mmu_symbol)
      
      cell_list_1 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_1"] #target cell type
      cell_list_2 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_2"] #target cell type
      cell_list_3 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_3"] #target cell type
      
      out_mat_1 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_1, geneids = gene_list_1, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_2 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_2, geneids = gene_list_2, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_3 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_3, geneids = gene_list_3, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      
      aux_mat <- assay(sce,"counts")[match(unique(c(gene_list_1,gene_list_2,gene_list_3)), rownames(sce)), match(c(cell_list_1, cell_list_2, cell_list_3), colnames(sce))] %>% as.matrix()
      
      aux_mat[match(gene_list_1, rownames(aux_mat)), match(cell_list_1, colnames(aux_mat))] <- out_mat_1
      aux_mat[match(gene_list_2, rownames(aux_mat)), match(cell_list_2, colnames(aux_mat))] <- out_mat_2
      aux_mat[match(gene_list_3, rownames(aux_mat)), match(cell_list_3, colnames(aux_mat))] <- out_mat_3
      
      write.table(as.matrix(aux_mat), file = paste0(sc3_multi_ct_perturbed_expr_dir_no_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

set.seed(789)
map2(effect_size, names(effect_size), ~ {
  es <- .x
  es_name <- .y
  dir.create(paste0(sc3_multi_ct_perturbed_expr_dir_ct_overlap, "/",es_name), showWarnings = FALSE)
  
  map2(multi_ct_gene_anno_ct_overlap, names(multi_ct_gene_anno_ct_overlap), ~ {
    expr_name <- .y
    sce <- expr_list[[expr_name]]
    coldata_df <- multi_ct_cell_anno[[expr_name]] %>% as.data.frame() %>% set_rownames(.$cellid) %>% select(new_cell_ontology_class, library_size) %>% set_colnames(c("cell_ontology_class","library_size"))
    
    map2(.x, names(.x), ~ {
      gs_name <- .y
      
      gene_list_1 <- filter(.x, is_causal_1 | is_ct_specific) %>% pull(mmu_symbol)
      gene_list_2 <- filter(.x, is_causal_2 | is_ct_specific) %>% pull(mmu_symbol)
      gene_list_3 <- filter(.x, is_causal_3 | is_ct_specific) %>% pull(mmu_symbol)
      
      cell_list_1 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_1"] #target cell type
      cell_list_2 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_2"] #target cell type
      cell_list_3 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_3"] #target cell type
      
      out_mat_1 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_1, geneids = gene_list_1, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_2 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_2, geneids = gene_list_2, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_3 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_3, geneids = gene_list_3, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      
      aux_mat <- assay(sce,"counts")[match(unique(c(gene_list_1,gene_list_2,gene_list_3)), rownames(sce)), match(c(cell_list_1, cell_list_2, cell_list_3), colnames(sce))] %>% as.matrix()
      
      aux_mat[match(gene_list_1, rownames(aux_mat)), match(cell_list_1, colnames(aux_mat))] <- out_mat_1
      aux_mat[match(gene_list_2, rownames(aux_mat)), match(cell_list_2, colnames(aux_mat))] <- out_mat_2
      aux_mat[match(gene_list_3, rownames(aux_mat)), match(cell_list_3, colnames(aux_mat))] <- out_mat_3
      
      write.table(as.matrix(aux_mat), file = paste0(sc3_multi_ct_perturbed_expr_dir_ct_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})

set.seed(012)
map2(effect_size, names(effect_size), ~ {
  es <- .x
  es_name <- .y
  dir.create(paste0(sc3_multi_ct_perturbed_expr_dir_causal_overlap, "/",es_name), showWarnings = FALSE)
  
  map2(multi_ct_gene_anno_causal_overlap, names(multi_ct_gene_anno_causal_overlap), ~ {
    expr_name <- .y
    sce <- expr_list[[expr_name]]
    coldata_df <- multi_ct_cell_anno[[expr_name]] %>% as.data.frame() %>% set_rownames(.$cellid) %>% select(new_cell_ontology_class, library_size) %>% set_colnames(c("cell_ontology_class","library_size"))
    
    map2(.x, names(.x), ~ {
      gs_name <- .y
      
      gene_list_1 <- filter(.x, is_causal | is_ct_specific_1) %>% pull(mmu_symbol)
      gene_list_2 <- filter(.x, is_causal | is_ct_specific_2) %>% pull(mmu_symbol)
      gene_list_3 <- filter(.x, is_causal | is_ct_specific_3) %>% pull(mmu_symbol)
      
      cell_list_1 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_1"] #target cell type
      cell_list_2 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_2"] #target cell type
      cell_list_3 <- rownames(coldata_df)[coldata_df$cell_ontology_class == "target_cell_type_3"] #target cell type
      
      out_mat_1 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_1, geneids = gene_list_1, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_2 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_2, geneids = gene_list_2, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      out_mat_3 <- perturb_count_matrix(sce = sce, covar_df = coldata_df, cellids = cell_list_3, geneids = gene_list_3, 
                                        effect_size_para = 2^es, copula_para_list = sc_para_list[[expr_name]]$copula, para_list = sc_para_list[[expr_name]]$para) %>% as.matrix()
      
      aux_mat <- assay(sce,"counts")[match(unique(c(gene_list_1,gene_list_2,gene_list_3)), rownames(sce)), match(c(cell_list_1, cell_list_2, cell_list_3), colnames(sce))] %>% as.matrix()
      
      aux_mat[match(gene_list_1, rownames(aux_mat)), match(cell_list_1, colnames(aux_mat))] <- out_mat_1
      aux_mat[match(gene_list_2, rownames(aux_mat)), match(cell_list_2, colnames(aux_mat))] <- out_mat_2
      aux_mat[match(gene_list_3, rownames(aux_mat)), match(cell_list_3, colnames(aux_mat))] <- out_mat_3
      
      write.table(as.matrix(aux_mat), file = paste0(sc3_multi_ct_perturbed_expr_dir_causal_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ), row.names = T, col.names = T, quote = F)
    })
  })
})


# write out parameter df 
multi_ct_output_dir_random <- here("results","causal_sim","sc3_multi_ct","random")

sc3_multi_ct_para_df_random <- expand_grid(es_name = names(effect_size),
                                           gs_name = names(z_score_list),
                                           expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(sc3_multi_ct_perturbed_expr_dir_random, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(sc3_multi_ct_gene_anno_dir_random, "/", expr_name,".",gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(sc3_multi_ct_cell_anno_dir, "/", expr_name, ".cell_anno.txt"),
         output_header = paste0(multi_ct_output_dir_random , "/", es_name, "/",gs_name,".",expr_name))


multi_ct_output_dir_no_overlap <- here("results","causal_sim","sc3_multi_ct","no_overlap")

sc3_multi_ct_para_df_no_overlap <- expand_grid(es_name = names(effect_size),
                                               gs_name = names(z_score_list),
                                               expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(sc3_multi_ct_perturbed_expr_dir_no_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(sc3_multi_ct_gene_anno_dir_no_overlap, "/", expr_name,".",gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(sc3_multi_ct_cell_anno_dir, "/", expr_name, ".cell_anno.txt"),
         output_header = paste0(multi_ct_output_dir_no_overlap , "/", es_name, "/",gs_name,".",expr_name))


multi_ct_output_dir_ct_overlap <- here("results","causal_sim","sc3_multi_ct","ct_overlap")

sc3_multi_ct_para_df_ct_overlap <- expand_grid(es_name = names(effect_size),
                                               gs_name = names(z_score_list),
                                               expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(sc3_multi_ct_perturbed_expr_dir_ct_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(sc3_multi_ct_gene_anno_dir_ct_overlap, "/", expr_name,".",gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(sc3_multi_ct_cell_anno_dir, "/", expr_name, ".cell_anno.txt"),
         output_header = paste0(multi_ct_output_dir_ct_overlap , "/", es_name, "/",gs_name,".",expr_name))


multi_ct_output_dir_causal_overlap <- here("results","causal_sim","sc3_multi_ct","causal_overlap")

sc3_multi_ct_para_df_causal_overlap <- expand_grid(es_name = names(effect_size),
                                                   gs_name = names(z_score_list),
                                                   expr_name = names(expr_list)) %>%
  mutate(expr_rda_file = paste0(expr_dir, "/", expr_name, ".rda"),
         expr_h5ad_file = paste0(h5ad_dir, "/", expr_name, ".h5ad"),
         perturbed_mat_file = paste0(sc3_multi_ct_perturbed_expr_dir_causal_overlap, "/",es_name, "/", gs_name,".",expr_name,".perturbed_mat.txt" ),
         gs_zscore_file = paste0(zscore_dir, "/", gs_name, ".genes.out"),
         gs_scdrs_file = paste0(scdrs_dir, "/", gs_name, ".gs"),
         magma_raw_file = paste0(magma_raw_dir, "/", gs_name, ".genes.raw"),
         gene_anno_file = paste0(sc3_multi_ct_gene_anno_dir_causal_overlap, "/", expr_name,".",gs_name, ".gene_anno.txt"),
         cell_anno_file = paste0(sc3_multi_ct_cell_anno_dir, "/", expr_name, ".cell_anno.txt"),
         output_header = paste0(multi_ct_output_dir_causal_overlap , "/", es_name, "/",gs_name,".",expr_name))


# write out parameter data frame
write.table(sc3_multi_ct_para_df_random , file = paste0(sc3_multi_ct_perturbed_expr_dir_random, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(sc3_multi_ct_para_df_no_overlap, file = paste0(sc3_multi_ct_perturbed_expr_dir_no_overlap, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(sc3_multi_ct_para_df_ct_overlap, file = paste0(sc3_multi_ct_perturbed_expr_dir_ct_overlap, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
write.table(sc3_multi_ct_para_df_causal_overlap, file = paste0(sc3_multi_ct_perturbed_expr_dir_causal_overlap, "/", "parameter_df.txt"), row.names = F, col.names = T, quote = F)
