#script to generate data for causal simulation
if (!require("here")){
  install.packages("here")
  library("here")
}
if (!require("magrittr")){
  install.packages("magrittr")
  library("magrittr")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
  library("tidyverse")
}
if (!require("SingleCellExperiment")){
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::install("SingleCellExperiment")
  library("SingleCellExperiment")
} 

#output directory
cell_anno_dir <- here("data","expr", "causal_sim", "standard_scdesign3_model")
cell_anno_dir_multi_ct <- here("data","expr","causal_sim", "multi_ct_scdesign3_model")

#### load random gene sets generated by null_sum_data_proc.R ####
expr_dir <- here("data","expr","null_sim","expr_rda_rs")

#load expression data
expr_list <- list.files(expr_dir) %>%
  set_names(gsub(pattern = ".rda", replacement = "", x = ., fixed = T)) %>%
  map(~{load(paste0(expr_dir,"/",.x)); return(sce)})  %>%
  map(~{colnames(.x) <- .x$cellid; .x})

#### sample datasets with 1 causal cell types ####
set.seed(98)
new_cell_anno_all <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map(~mutate(.x, is_target = ifelse(1:n() %in% sample(n(), 100), T, F))) %>%
  map(~mutate(.x, new_cell_ontology_class = ifelse(is_target, "target_cell_type", cell_ontology_class))) %>%
  map2(expr_list, ~mutate(.x, library_size = colSums(assay(.y,"counts")))) 

map2(new_cell_anno_all, names(new_cell_anno_all), 
     ~write.table(.x, file = paste0(cell_anno_dir, "/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))

#### sample datasets with 3 causal cell types ####
set.seed(98)
multi_ct_target_cell_1 <- map(expr_list, ~sample(colnames(.x), size = 100))
multi_ct_target_cell_2 <- map2(expr_list,multi_ct_target_cell_1, ~sample(colnames(.x)[!colnames(.x) %in% .y], size = 100))
multi_ct_target_cell_3 <- map2(multi_ct_target_cell_1, multi_ct_target_cell_2, ~cbind(.x, .y)) %>%
  map2(expr_list, ~sample(colnames(.y)[!colnames(.y) %in% .x], size = 100))

multi_ct_cell_anno <- map(expr_list, ~colData(.x)) %>%
  map(~as_tibble(.x)) %>%
  map2(expr_list, ~mutate(.x, library_size = colSums(assay(.y,"counts"))))  %>%
  map(~mutate(.x, new_cell_ontology_class = cell_ontology_class)) %>%
  map2(multi_ct_target_cell_1, ~mutate(.x, new_cell_ontology_class = ifelse(cellid %in% .y, "target_cell_type_1",new_cell_ontology_class))) %>%
  map2(multi_ct_target_cell_2, ~mutate(.x, new_cell_ontology_class = ifelse(cellid %in% .y, "target_cell_type_2",new_cell_ontology_class))) %>%
  map2(multi_ct_target_cell_3, ~mutate(.x, new_cell_ontology_class = ifelse(cellid %in% .y, "target_cell_type_3",new_cell_ontology_class)))

map2(multi_ct_cell_anno , names(multi_ct_cell_anno), 
     ~write.table(.x, file = paste0(cell_anno_dir_multi_ct, "/", .y,".cell_anno.txt"), quote = F,row.names = F,sep="\t"))
