#Preprocessing steps for Tabula sapiens data set

##### 1. load packages and data#######
### 1 load packages
if(!require("Seurat")){
  install.packages("Seurat")
  library("Seurat")
}
if (!require("here")){
  install.packages("here")
  library("here")
}
if (!require("magrittr")){
  install.packages("magrittr")
  library("magrittr")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
  library("tidyverse")
}
if (!require("SingleCellExperiment")){
  if (!requireNamespace("BiocManager", quietly = TRUE)){
    install.packages("BiocManager")
  }
  BiocManager::install("SingleCellExperiment")
  library("SingleCellExperiment")
} 
if (!require("zellkonverter")){
  if (!requireNamespace("BiocManager", quietly = TRUE)){
    install.packages("BiocManager")
  }
  BiocManager::install("zellkonverter")
  library("zellkonverter")
} 
if (!require("seismicGWAS")){
  if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
  }
  devtools::install_github("ylaboratory/seismicGWAS")
  library("seismicGWAS")
}

#####load data and filter data#######
###1 load data
#data file
ts_obj <- readH5AD(here("raw","expr","Tabula_sapiens","TabulaSapiens.h5ad"),reader = "R")

#annotation file
load(here("data","ref","mapping","mmu_hsa_mapping.rda"))
source(here("src","tools","munge_sce_mat.R"))

#remove assays that will never be used: keep the decontaminated counts
assays(ts_obj)[c("raw_counts","X")] <- NULL
names(assays(ts_obj)) <- "counts"

#print out cell ontology class list
cell_ontology_class <- colData(ts_obj) %>% as_tibble %>% distinct(cell_ontology_class)
write.table(cell_ontology_class, here("data","expr","Tabula_sapiens","all_cell_ontology_class.csv"),row.names = F,quote = F)

cell_ontology_anno <- read.csv(here("data","expr","Tabula_sapiens","all_cell_ontology_class.annotated.new.csv")) %>% as_tibble()

#filter out cell ontology class without annotation
ts_obj <- ts_obj[,which(ts_obj$cell_ontology_class %in% cell_ontology_anno$cell_ontology_class)]

#add column annotation
colData(ts_obj)$cell_ontology_id <- cell_ontology_anno$cl_term[match(ts_obj$cell_ontology_class, cell_ontology_anno$cell_ontology_class)]
colData(ts_obj)$official_name <- cell_ontology_anno$official_name[match(ts_obj$cell_ontology_class, cell_ontology_anno$cell_ontology_class)]
colData(ts_obj)$cluster_name <- paste0(ts_obj$organ_tissue, ".", ts_obj$official_name)

#filter out cells of strange annotation
ts_obj <- ts_obj[,which(ts_obj$cell_ontology_class!="hepatocyte" | ts_obj$organ_tissue!="Heart" )]
#filter out cells that are not generated by 10x
ts_obj <- ts_obj[, ts_obj$method=="10X"] 

#add column and rownames 
gene_anno <- rowData(ts_obj) %>% 
  as_tibble() %>%
  mutate(ensembl = strsplit(ensemblid, split=".", fixed=T) %>% map(~.x[1]) %>% unlist)
rownames(ts_obj) <- gene_anno$ensemblid
ts_obj <- munge_sce_mat(ts_obj, gene_anno %>% select(ensemblid,ensembl)) #merge by ensemblid (sum)

#add something to the colData
rowData(ts_obj) <- gene_anno %>%
  filter(ensembl %in% rownames(ts_obj)) %>%
  distinct(ensembl, gene_symbol) %>%
  mutate(ensembl = factor(ensembl, levels = rownames(ts_obj))) %>%
  arrange(ensembl) %>%
  mutate(ensembl = as.character(ensembl)) %>%
  DataFrame() %>%
  set_rownames(.$ensembl)

#save 
save(ts_obj, file = here("data","expr","Tabula_sapiens","TS_clean.new.rda"))

