if (!require("here")){
  install.packages("here")
  library("here")
}
if (!require("magrittr")){
  install.packages("magrittr")
  library("magrittr")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
  library("tidyverse")
}

#load objects
load(here("data","ref","mapping","mmu_hsa_mapping.rda"))

##### load random gene sets generated by null_sum_data_proc.R ####
zscore_dir <- here("data","gwas","causal_sim","zscore")

#load all random gene sets generated
z_score_list <- list.files(zscore_dir) %>%
  set_names(gsub(pattern = ".genes.out", replacement = "", x = ., fixed = T)) %>%
  map(~read.table(file=paste0(zscore_dir,"/",.x), header = T)) %>%
  map(~left_join(.x, distinct(mmu_hsa_mapping, hsa_entrez, mmu_symbol), by = c("GENE"="hsa_entrez"))) #join with gene mapping

#get the .05 FDR genes
num_sig_genes <- z_score_list %>%
  map(~drop_na(.x,mmu_symbol)) %>%
  map(~mutate(.x, FDR = p.adjust(P, method = "BH"))) %>%
  map(~nrow(filter(.x, FDR<=0.05)))

ggplot(data.frame(gene_set = factor(names(num_sig_genes), levels = paste0("gs_",1:10)), num_sig_genes = unlist(num_sig_genes)), aes(x = gene_set, y = num_sig_genes )) +
  geom_bar(stat="identity") +
  theme_classic()
